name: ars_dialog
description: Dialog material widget with blur background and popup animation
version: 1.0.6
homepage: https://github.com/arsamme/flutter-dialogs

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
